# .github/workflows/ci.yml
name: Dummy CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Use something stable

      - name: Install dependencies (if any)
        run: |
          if [ -s requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No dependencies to install"
          fi

      - name: Run dummy test
        run: echo "CI passed 🎉"
